### ISSUE TITLE
Groundcheck is false on prop_dynamic/prop_physics

### ISSUE THREAD

**Issue by LauraWebdev** [DevulTj/sbox-template.fps#4]
Great template, thanks for working on it!

I've encountered a small issue, when standing on a prop_physics/prop_dynamic, the player is considered flying/not grounded.

Example:
![image](https://user-images.githubusercontent.com/7365286/210153290-c99cdb04-c5d5-4124-918e-ff2c66a32d39.png)

**Comment by DevulTj** [comment]
Fixed, thanks!
